# Stage 1
# Base image
FROM node:18.16.0 AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --production

# Copy the application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Stage 2
# Production image
FROM node:18.16.0-alpine

# Set the working directory
WORKDIR /app

# Install serve to run the production build of the React application
RUN npm install -g serve

# Copy the built React application from the build stage
COPY --from=build /app/build ./build

# Expose the port that the application will run on
EXPOSE 3000

# Set the command to run the application
CMD serve -s build -l 3000
