# Base image
FROM node:18.16.0-alpine

# Set the working directory
WORKDIR /api

# Copy the proxy server files to the working directory
COPY /server/index.js /server/queries.js package.json ./

# Install dependencies
RUN npm install --production

# Copy the working directory 
COPY . .

# Expose the port that the proxy server will run on
EXPOSE 3001

# Set the command to run the proxy server
CMD node index.js